// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallDeb(arg1) {
  return window['go']['main']['App']['InstallDeb'](arg1);
}

export function SelectDebFile() {
  return window['go']['main']['App']['SelectDebFile']();
}
