// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InstallDeb(arg1:string):Promise<main.InstallResult>;

export function SelectDebFile():Promise<string>;
